#pragma kernel Advect

#include "../Common.hlsl"

RWStructuredBuffer<Particle> _ParticleBufferRW;

[numthreads(128, 1, 1)]
void Advect(uint3 thread_id : SV_DispatchThreadID)
{
    RETURN_IF_INVALID(thread_id);

    const uint p_id = thread_id.x;

    Particle p = _ParticleBufferRW[p_id];

    p.position += p.velocity * _DeltaTime;

    ClampPosition(p.position, _GridMin, _GridMax, _GridSpacing);

    _ParticleBufferRW[p_id] = p;
}